stages: [deploy]

pages:
  image: alpine:3.19
  stage: deploy
  before_script:
    - apk add --no-cache rsync
  script:
    - rm -rf public && mkdir public
    - rsync -a \
        --exclude='public' \
        --exclude='.git' \
        --exclude='.gitlab-ci.yml' \
        ./ public/
    - test -f public/index.html || printf '<!doctype html><meta charset="utf-8"><title>OK</title><h1>Deployed</h1>' > public/index.html
  artifacts:
    paths: [public]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
