stages: [deploy]

pages:
  image: alpine:3.19
  stage: deploy
  script:
    - rm -rf public && mkdir public
    - cp -r * public/
    - rm -rf public/.git public/.gitlab-ci.yml public/public
  artifacts:
    paths: [public]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
