stages: [deploy]

pages:
  image: alpine:3.19
  stage: deploy
  script:
    - rm -rf public && mkdir public
    - |
      find . -maxdepth 1 -mindepth 1 \
        ! -name '.' \
        ! -name 'public' \
        ! -name '.git' \
        ! -name '.gitlab-ci.yml' \
        -exec cp -r {} public/ \;
  artifacts:
    paths: [public]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
