stages: [deploy]

pages:
  image: busybox:1.36
  stage: deploy
  script:
    - rm -rf public && mkdir public
    # Copy top-level files/dirs EXCEPT public/.git/.gitlab-ci.yml
    - find . -mindepth 1 -maxdepth 1 \
        ! -name '.' \
        ! -name 'public' \
        ! -name '.git' \
        ! -name '.gitlab-ci.yml' \
        -exec cp -r {} public/ \; || true
    # Ensure a homepage exists
    - test -f public/index.html || printf '<!doctype html><meta charset="utf-8"><title>OK</title><h1>Deployed</h1><p><a href="blog/">Blog</a> • <a href="elowen/">Elowen</a></p>' > public/index.html
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
