stages: [deploy]

pages:
  image: alpine:3.19
  stage: deploy
  script:
    - set -euo pipefail
    - rm -rf public && mkdir public
    # Copy everything at repo root EXCEPT: public, .git, and the CI file itself
    - find . -mindepth 1 -maxdepth 1 \
        ! -name public \
        ! -name .git \
        ! -name .gitlab-ci.yml \
        -exec cp -r {} public/ \;
  artifacts:
    paths: [public]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

