stages:
  - deploy

pages:
  stage: deploy
  image: alpine:3.20
  script:
    - mkdir -p public
    - apk add --no-cache bash
    - bash -lc 'shopt -s dotglob; for p in *; do case "$p" in .git|.github|.gitlab-ci.yml) continue;; *) cp -a "$p" public/ ;; esac; done'
    - test -f public/CNAME && echo "CNAME: $(cat public/CNAME)" || true
  artifacts:
    paths:
      - public
  only:
    - main
