stages: [deploy]
pages:
  stage: deploy
  script:
    - mkdir -p public
    - rsync -a --delete --exclude='.git' --exclude='public' ./ public/
  artifacts:
    paths:
      - public
  only:
    - main
