name: Deploy static site to GitHub Pages (gh-pages branch)
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare artifact (copy entire repo)
        run: |
          mkdir -p site
          shopt -s dotglob
          for p in *; do
            case "$p" in
              .git|.github|.gitlab-ci.yml) continue;;
              *) cp -a "$p" site/ ;;
            esac
          done
          [ -f public/CNAME ] && cp -a public/CNAME site/ || true
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages
